Deprecate support for (n, 1)-shaped error arrays in errorbar().
errorbar() documents that it supports the following shapes for error
arrays:

    - scalar: Symmetric +/- values for all data points.
    - shape(N,): Symmetric +/-values for each data point.
    - shape(2,N): Separate - and + values for each bar. First row
        contains the lower errors, the second row contains the
        upper errors.
    - *None*: No errorbar.

Actually it also supports (N, 1)-shaped arrays (treating them as shape
(N,)), but this support is broken for N=2 *at least* since Matplotlib
1.5:

    N = 2; errorbar(range(N), range(N), np.arange(N).reshape((N, 1)))
    ...
    ValueError: In safezip, len(args[0])=2 but len(args[1])=1

(This works for other values of N.)

Instead of further maintaining code to handle that case, just deprecate
it (no one has apparently noticed the N=2 bug, suggesting that this
(mis)feature is not much used anyways).