Don't try to use the colorbar formatter to format RGBA data.
A colorbar doesn't make much sense for RGBA data, but matplotlib does
allow one to be constructed; when formatting the cursor data for a RGBA
image we must be careful to not use the colorbar formatter.

Otherwise, after `plt.imshow(np.random.rand(5, 5, 3)); plt.colorbar()`,
when moving the mouse cursor over the image, we get
```
<elided>
  File "/usr/lib/python3.7/site-packages/matplotlib/ticker.py", line 604, in format_data_short
    return '%-12g' % value
  File "/usr/lib/python3.7/site-packages/numpy/ma/core.py", line 4296, in __float__
    raise TypeError("Only length-1 arrays can be converted "
TypeError: Only length-1 arrays can be converted to Python scalars
```