Clarify missing-property error message.
The error message is modelled like CPython's normal AttributeError
message ('foo' object has no attribute 'bar').