cairo backends do not support blitting; mark them as such.
Trying to run a blitting animation example on gtk3cairo currently fails
with

    AttributeError: 'FigureCanvasGTK3Cairo' object has no attribute 'copy_from_bbox'

While blitting can be made to work for e.g. qt5cairo, it cannot be for
gtk3cairo which relies on gtk's windowing code to handle us a cairo
context to directly draw on when a draw event occurs: the animation
blitting code fundamentally assumes that it can modify the underlying
buffer whenever it wants and that the windowing system simply displayes
that buffer at each draw event.