Remove newline from start of deprecation warnings
This breaks the summary from Pytest when warnings are errors, as then
you just get a bunch of:
```
FAILED lib/matplotlib/tests/test_getattr.py::test_getattr[matplotlib.afm] - matplotlib._api.deprecation.MatplotlibDeprecationWarning:
```
with no real context as to the problem.

Also, as noted at the original PR [1], it makes setting `filterwarnings`
more complicated.

[1] https://github.com/matplotlib/matplotlib/pull/11224#issuecomment-435167674