Fix Pillow import in testing.
The expected import is `from PIL import Image`, and if you import the
compare function directly, it will fail:
```
>>> from matplotlib.testing.compare import compare_images
>>> compare_images('a.png', 'b.png', 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../matplotlib/testing/compare.py", line 394, in compare_images
    expected_image = np.asarray(PIL.Image.open(expected).convert("RGB"))
AttributeError: module 'PIL' has no attribute 'Image'
```

It only works in our test suite because some other file does it
correctly.