TST: some tex tests also need to guard against missing gs
Also fixed a problem in an error message when bytes were appended to
a string (fails on py3.x) by using %.

One of the errors before:

======================================================================
ERROR: matplotlib.tests.test_backend_ps.test_savefig_to_stringio_with_usetex
----------------------------------------------------------------------
Traceback (most recent call last):
  File "lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "lib\matplotlib\testing\decorators.py", line 152, in wrapped_callable

    func(*args, **kwargs)
  File "lib\matplotlib\testing\decorators.py", line 55, in failer
    result = f(*args, **kwargs)
  File "lib\matplotlib\tests\test_backend_ps.py", line 77, in test_savefig_to_stringio_with_usetex
    _test_savefig_to_stringio()
  File "lib\matplotlib\tests\test_backend_ps.py", line 40, in _test_savefig_to_stringio
    fig.savefig(buffer, format=format)
  File "lib\matplotlib\figure.py", line 1698, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "lib\matplotlib\backend_bases.py", line 2232, in print_figure
    **kwargs)
  File "lib\matplotlib\backends\backend_ps.py", line 985, in print_ps
    return self._print_ps(outfile, 'ps', *args, **kwargs)
  File "lib\matplotlib\backends\backend_ps.py", line 1012, in _print_ps
    **kwargs)
  File "lib\matplotlib\backends\backend_ps.py", line 1376, in _print_figure_tex
    rotated=psfrag_rotated)
  File "lib\matplotlib\backends\backend_ps.py", line 1539, in gs_distill
    raise RuntimeError(m % output)
RuntimeError: ghostscript was not able to process your image.
Here is the full report generated by ghostscript:

b''